// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/users/list": {
    params: {};
  };
  "/dashboard/users/new": {
    params: {};
  };
  "/dashboard/users/preregisters": {
    params: {};
  };
  "/dashboard/hostels": {
    params: {};
  };
  "/dashboard/hostels/list": {
    params: {};
  };
  "/dashboard/hostels/new": {
    params: {};
  };
  "/dashboard/hostels/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/hostels/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/hostels/reservations": {
    params: {};
  };
  "/dashboard/hostels/reservations/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/hostels/statistics": {
    params: {};
  };
  "/dashboard/admins": {
    params: {};
  };
  "/dashboard/admins/list": {
    params: {};
  };
  "/dashboard/admins/new": {
    params: {};
  };
  "/dashboard/admins/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/admins/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/services": {
    params: {};
  };
  "/dashboard/services/list": {
    params: {};
  };
  "/dashboard/services/new": {
    params: {};
  };
  "/dashboard/services/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/services/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/services/hostel-services": {
    params: {};
  };
  "/dashboard/services/hostel-services/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/services/hostel-services/new": {
    params: {};
  };
  "/dashboard/services/hostel-services/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/services/schedules": {
    params: {};
  };
  "/dashboard/services/reservations": {
    params: {};
  };
  "/dashboard/services/reservations/new": {
    params: {};
  };
  "/dashboard/services/reservations/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/inventory": {
    params: {};
  };
  "/dashboard/inventory/list": {
    params: {};
  };
  "/dashboard/inventory/new": {
    params: {};
  };
  "/dashboard/inventory/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/inventory/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/inventory/items": {
    params: {};
  };
  "/dashboard/inventory/:id/items/new": {
    params: {
      "id": string;
    };
  };
  "/dashboard/inventory/items/new-item": {
    params: {};
  };
  "/dashboard/inventory/items/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/dashboard/inventory/low-stock": {
    params: {};
  };
  "/dashboard/reservations": {
    params: {};
  };
  "/404": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/dashboard/users" | "/dashboard/users/list" | "/dashboard/users/new" | "/dashboard/users/preregisters" | "/dashboard/hostels" | "/dashboard/hostels/list" | "/dashboard/hostels/new" | "/dashboard/hostels/edit/:id" | "/dashboard/hostels/detail/:id" | "/dashboard/hostels/reservations" | "/dashboard/hostels/reservations/detail/:id" | "/dashboard/hostels/statistics" | "/dashboard/admins" | "/dashboard/admins/list" | "/dashboard/admins/new" | "/dashboard/admins/edit/:id" | "/dashboard/admins/detail/:id" | "/dashboard/services" | "/dashboard/services/list" | "/dashboard/services/new" | "/dashboard/services/edit/:id" | "/dashboard/services/detail/:id" | "/dashboard/services/hostel-services" | "/dashboard/services/hostel-services/detail/:id" | "/dashboard/services/hostel-services/new" | "/dashboard/services/hostel-services/edit/:id" | "/dashboard/services/schedules" | "/dashboard/services/reservations" | "/dashboard/services/reservations/new" | "/dashboard/services/reservations/detail/:id" | "/dashboard/inventory" | "/dashboard/inventory/list" | "/dashboard/inventory/new" | "/dashboard/inventory/detail/:id" | "/dashboard/inventory/edit/:id" | "/dashboard/inventory/items" | "/dashboard/inventory/:id/items/new" | "/dashboard/inventory/items/new-item" | "/dashboard/inventory/items/:id/edit" | "/dashboard/inventory/low-stock" | "/dashboard/reservations" | "/404";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/users" | "/dashboard/users/list" | "/dashboard/users/new" | "/dashboard/users/preregisters" | "/dashboard/hostels" | "/dashboard/hostels/list" | "/dashboard/hostels/new" | "/dashboard/hostels/edit/:id" | "/dashboard/hostels/detail/:id" | "/dashboard/hostels/reservations" | "/dashboard/hostels/reservations/detail/:id" | "/dashboard/hostels/statistics" | "/dashboard/admins" | "/dashboard/admins/list" | "/dashboard/admins/new" | "/dashboard/admins/edit/:id" | "/dashboard/admins/detail/:id" | "/dashboard/services" | "/dashboard/services/list" | "/dashboard/services/new" | "/dashboard/services/edit/:id" | "/dashboard/services/detail/:id" | "/dashboard/services/hostel-services" | "/dashboard/services/hostel-services/detail/:id" | "/dashboard/services/hostel-services/new" | "/dashboard/services/hostel-services/edit/:id" | "/dashboard/services/schedules" | "/dashboard/services/reservations" | "/dashboard/services/reservations/new" | "/dashboard/services/reservations/detail/:id" | "/dashboard/inventory" | "/dashboard/inventory/list" | "/dashboard/inventory/new" | "/dashboard/inventory/detail/:id" | "/dashboard/inventory/edit/:id" | "/dashboard/inventory/items" | "/dashboard/inventory/:id/items/new" | "/dashboard/inventory/items/new-item" | "/dashboard/inventory/items/:id/edit" | "/dashboard/inventory/low-stock" | "/dashboard/reservations";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/dashboard/users/index.tsx": {
    id: "routes/dashboard/users/index";
    page: "/dashboard/users";
  };
  "routes/dashboard/users/list.tsx": {
    id: "routes/dashboard/users/list";
    page: "/dashboard/users/list";
  };
  "routes/dashboard/users/new.tsx": {
    id: "routes/dashboard/users/new";
    page: "/dashboard/users/new";
  };
  "routes/dashboard/users/preregisters.tsx": {
    id: "routes/dashboard/users/preregisters";
    page: "/dashboard/users/preregisters";
  };
  "routes/dashboard/hostels/index.tsx": {
    id: "routes/dashboard/hostels/index";
    page: "/dashboard/hostels";
  };
  "routes/dashboard/hostels/list.tsx": {
    id: "routes/dashboard/hostels/list";
    page: "/dashboard/hostels/list";
  };
  "routes/dashboard/hostels/new.tsx": {
    id: "routes/dashboard/hostels/new";
    page: "/dashboard/hostels/new";
  };
  "routes/dashboard/hostels/edit.tsx": {
    id: "routes/dashboard/hostels/edit";
    page: "/dashboard/hostels/edit/:id";
  };
  "routes/dashboard/hostels/detail.tsx": {
    id: "routes/dashboard/hostels/detail";
    page: "/dashboard/hostels/detail/:id";
  };
  "routes/dashboard/hostels/reservations.tsx": {
    id: "routes/dashboard/hostels/reservations";
    page: "/dashboard/hostels/reservations";
  };
  "routes/dashboard/hostels/reservations/detail.tsx": {
    id: "routes/dashboard/hostels/reservations/detail";
    page: "/dashboard/hostels/reservations/detail/:id";
  };
  "routes/dashboard/hostels/statistics.tsx": {
    id: "routes/dashboard/hostels/statistics";
    page: "/dashboard/hostels/statistics";
  };
  "routes/dashboard/admins/index.tsx": {
    id: "routes/dashboard/admins/index";
    page: "/dashboard/admins";
  };
  "routes/dashboard/admins/list.tsx": {
    id: "routes/dashboard/admins/list";
    page: "/dashboard/admins/list";
  };
  "routes/dashboard/admins/new.tsx": {
    id: "routes/dashboard/admins/new";
    page: "/dashboard/admins/new";
  };
  "routes/dashboard/admins/edit.tsx": {
    id: "routes/dashboard/admins/edit";
    page: "/dashboard/admins/edit/:id";
  };
  "routes/dashboard/admins/detail.tsx": {
    id: "routes/dashboard/admins/detail";
    page: "/dashboard/admins/detail/:id";
  };
  "routes/dashboard/services/index.tsx": {
    id: "routes/dashboard/services/index";
    page: "/dashboard/services";
  };
  "routes/dashboard/services/list.tsx": {
    id: "routes/dashboard/services/list";
    page: "/dashboard/services/list";
  };
  "routes/dashboard/services/new.tsx": {
    id: "routes/dashboard/services/new";
    page: "/dashboard/services/new";
  };
  "routes/dashboard/services/edit.tsx": {
    id: "routes/dashboard/services/edit";
    page: "/dashboard/services/edit/:id";
  };
  "routes/dashboard/services/detail.tsx": {
    id: "routes/dashboard/services/detail";
    page: "/dashboard/services/detail/:id";
  };
  "routes/dashboard/services/hostel-services.tsx": {
    id: "routes/dashboard/services/hostel-services";
    page: "/dashboard/services/hostel-services";
  };
  "routes/dashboard/services/hostel-services/detail.tsx": {
    id: "routes/dashboard/services/hostel-services/detail";
    page: "/dashboard/services/hostel-services/detail/:id";
  };
  "routes/dashboard/services/hostel-services/new.tsx": {
    id: "routes/dashboard/services/hostel-services/new";
    page: "/dashboard/services/hostel-services/new";
  };
  "routes/dashboard/services/hostel-services/edit.tsx": {
    id: "routes/dashboard/services/hostel-services/edit";
    page: "/dashboard/services/hostel-services/edit/:id";
  };
  "routes/dashboard/services/schedules.tsx": {
    id: "routes/dashboard/services/schedules";
    page: "/dashboard/services/schedules";
  };
  "routes/dashboard/services/reservations.tsx": {
    id: "routes/dashboard/services/reservations";
    page: "/dashboard/services/reservations";
  };
  "routes/dashboard/services/reservations/new.tsx": {
    id: "routes/dashboard/services/reservations/new";
    page: "/dashboard/services/reservations/new";
  };
  "routes/dashboard/services/reservations/detail.tsx": {
    id: "routes/dashboard/services/reservations/detail";
    page: "/dashboard/services/reservations/detail/:id";
  };
  "routes/dashboard/inventory/index.tsx": {
    id: "routes/dashboard/inventory/index";
    page: "/dashboard/inventory";
  };
  "routes/dashboard/inventory/list.tsx": {
    id: "routes/dashboard/inventory/list";
    page: "/dashboard/inventory/list";
  };
  "routes/dashboard/inventory/new.tsx": {
    id: "routes/dashboard/inventory/new";
    page: "/dashboard/inventory/new";
  };
  "routes/dashboard/inventory/detail.tsx": {
    id: "routes/dashboard/inventory/detail";
    page: "/dashboard/inventory/detail/:id";
  };
  "routes/dashboard/inventory/edit.tsx": {
    id: "routes/dashboard/inventory/edit";
    page: "/dashboard/inventory/edit/:id";
  };
  "routes/dashboard/inventory/items.tsx": {
    id: "routes/dashboard/inventory/items";
    page: "/dashboard/inventory/items";
  };
  "routes/dashboard/inventory/items/new.tsx": {
    id: "routes/dashboard/inventory/items/new";
    page: "/dashboard/inventory/:id/items/new";
  };
  "routes/dashboard/inventory/items/new-item.tsx": {
    id: "routes/dashboard/inventory/items/new-item";
    page: "/dashboard/inventory/items/new-item";
  };
  "routes/dashboard/inventory/items/edit.tsx": {
    id: "routes/dashboard/inventory/items/edit";
    page: "/dashboard/inventory/items/:id/edit";
  };
  "routes/dashboard/inventory/low-stock.tsx": {
    id: "routes/dashboard/inventory/low-stock";
    page: "/dashboard/inventory/low-stock";
  };
  "routes/dashboard/reservations/index.tsx": {
    id: "routes/dashboard/reservations/index";
    page: "/dashboard/reservations";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/404";
  };
};